### ISSUE TITLE
Ajouter de la Javadoc

### ISSUE THREAD

**Issue by FlorentClarret** [BenoitLoic/Project2_OpenClassroom#5]
La documentation est importante, presque indispensable. Elle est souvent délaissée, et ne devrait pas.

Il est nécessaire de faire de la javadoc pour, au minimum, tout ce qui est déclaré `public`.

N'oublie pas, la doc est importante pour les autres... mais aussi pour toi !

**Comment by FlorentClarret** [comment]
N'hésite pas à rajouter des "one line comments" via `//` pour avoir des commentaires supplémentaires

**Comment by BenoitLoic** [comment]
alors je sais qu'on en a parlé hier, mais je vois pas trop quoi écrire dans les @throws, parce que juste mettre l'exception renvoyé (IOException) juste en disant que c'est dû au writer me semble un peu léger.

**Comment by FlorentClarret** [comment]
Tu peux simplement dire que c'est en cas de problème lors de la lecture du fichier. C'est une exception assez standard donc ça devrait être suffisant. De toute façon, si elle claque elle sera très précise

**Comment by FlorentClarret** [comment]
Sur ta javadoc il te manque quelque chose : 

``` java
    /**
     * @param map Map <String, Integer> that will be written in output file
     * @throws IOException for FileWriter
     */
    public void outputWriter(Map<String, Integer> map) throws IOException {
        try (FileWriter writer = new FileWriter(outputFilepath)) {


            for (Map.Entry<String, Integer> entry : map.entrySet()) {

                writer.write(entry.getKey() + " : " + entry.getValue() + "\n");

            }
        }
    }
```

Il te faut une ligne de description de ce que fait la méthode. Exemple : 

``` java
    /**
     * This methods will print the input map into a file.
     * @param map Map <String, Integer> that will be written in output file
     * @throws IOException for FileWriter
     */
    public void outputWriter(Map<String, Integer> map) throws IOException {
```
Au passage : outputWriter, c'est pas top comme nom ;)

**Comment by FlorentClarret** [comment]
Hésite pas à regarder ce cours-ci : https://openclassrooms.com/fr/courses/1115306-presentation-de-la-javadoc
