### ISSUE TITLE
Utilisation de polymorphisme

### ISSUE THREAD

**Issue by FlorentClarret** [BenoitLoic/Project2_OpenClassroom#6]
Le quoi ? :p

Prenons un exemple tiré de ton projet : 

``` java 
    public HashMap<String, Integer> countFrequencies(ArrayList<String> list)  {
        HashMap<String, Integer> myHashMap = new HashMap<>();
        for (String i : list) {
            Integer j = myHashMap.get(i); //
            myHashMap.put(i, (j == null) ? 1 : j + 1);
        } 
        return myHashMap;
    }
```

Cette méthode peut poser problème car elle retourne un objet de type `HashMap`. Cela signifie que tous ceux qui t'appelent doivent utiliser cette classe. Si demain tu souhaites utiliser une `LinkedHashMap` (parce que pourquoi pas), toutes les méthodes qui utilisent cette méthode devront être modifiées.

Il existe une méthode simple pour solutionner ce problème : utiliser le polymorphisme. On peut en reparler pendant une session si tu le souhaites !

**Comment by BenoitLoic** [comment]
Oulala... j'ai beau essayer je comprend pas ce qu'il faut faire. La seule modif que j'ai trouvé à faire c'est : `public class CountFrequencies {


    public Map<String, Integer> countFrequencies(List<?> list) {

        Map<String, Integer> counter = new HashMap<>();


        for (Object symptom : list) {

            Integer frequency = counter.get(symptom);
            counter.put((String) symptom, (frequency == null) ? 1 : frequency + 1);

        }
        return counter;


    }

}`

`public class CountDataFrequencies extends CountFrequencies{


    public HashMap<String, Integer> countFrequencies(ArrayList<String> list) {

        HashMap<String, Integer> counter = new HashMap<>();



        return counter;


    }

}`

**Comment by FlorentClarret** [comment]
Si ta modification est la suivante : 

``` java 
public Map<String, Integer> countFrequencies(List<?> list) {
    Map<String, Integer> counter = new HashMap<>();
    for (Object symptom : list) {
        Integer frequency = counter.get(symptom);
        counter.put((String) symptom, (frequency == null) ? 1 : frequency + 1);
    }
    return counter;
}
```

C'est à dire :

- Passer de ArrayList à List
- Passer de HashMap à Map

Alors c'est bien ça ! 

Par contre ton `List<?> list` avec le wildcard (le point d"interrogation) est étrange. On en parle demain soir !
